### ISSUE TITLE
Expressions

### ISSUE THREAD

**Issue by jnunemaker** [flippercloud/flipper#557]
I'll try to communicate more soon. But the tldr is @orderedlist, @bkeepers and I are working on a new feature (for www.flippercloud.io and open source) we're calling "rules" ([branch](https://github.com/jnunemaker/flipper/compare/learn-the-rules)). This issue is just so we can keep track of the work together on the open source side.

## ActiveRecord Migration

Those using the `flipper-active_record` adapter will want to migrate the database so it can store JSON expressions:

```
$ rails generate migration change_flipper_gates_value_to_text
```

```ruby
  def up
    change_column :flipper_gates, :value, :text
  end

  def down
    change_column :flipper_gates, :value, :string
  end
```

## TODO 

* [x] Support single `Rule`
* [x] Support multiple rules through `And` rule
* [x] Support multiple rules through `Any` rule
* [x] Refactor `from_hash` and other case statements
* [x] Get all specs and tests passing
* [x] Add enable_* and disable_* methods to `Flipper`, `Flipper::DSL` and `Flipper::Feature`
* [x] Add Rule equality like `==` and `eql?`
* [x] Make real ruby classes for types in left, operator and right
* [x] Add examples for `Rule`, `Any`, and `And`
* [x] Make all types consistent in capitalization (currently Condition and property, string, etc.)
* [x] Add rule shortcuts to make it easier to use them
* [x] Add new shared adapter spec(s) to shared adapter tests
* [x] Update feature synchronizer to include :json/rules
* [x] Update api docs
* [x] Update gate docs
* [x] Error in AR/Sequel if `value` column is not `text`
* [x] Add `Flipper.add_rule` and `Flipper.remove_rule` for easy adding and removing
* [x] What about floats? Should we use number instead of integer as the type and support floats? Or add float as type?  
* [x] Document AR/Sequel migration to convert `value` from `string` to `text`

## After releasing beta

* [ ] Enforce types for operators. in requires array on right. percentage requires string on left and integer/number on right, etc. Make this easy to pass to javascript front end for @orderedlist. 
* [ ] Enforce string, number, null, boolean, etc. or array of former for flipper_properties somehow (maybe skip invalid and warn to avoid blowing up? or blow up in dev but skip in prod?)
* [x] Ensure that time based enablements are easy (enable when now epoch > int or now > date time)
* [x] Make it possible to enable/disable rules in www.flippercloud.io
* [ ] Update readme to include rules

## Someday 

* [ ] Make it easier to work with date/time for scheduled releases (things like "enabled if Monday-Friday 9am-5pm)", just an and expression with day of week and time of day extraction that do gt, gte, lt, lte comparisions, etc.)
* [ ] Make it possible to do repeating time based enablements (enable if M-F 9a-5pm, etc.) 
* [x] Add feature type that passes actor and checks `enabled?` so you can do stuff like [feature dependencies](https://gist.github.com/jnunemaker/e4bdd4b2cce98499bdad1c7a97f5acfa)

**Comment by marknuzz** [comment]
What does a "Rule" do?

**Comment by jnunemaker** [comment]
@marknuzz check out [this file](https://github.com/jnunemaker/flipper/blob/b3f49d1a05e1bd4b34ce3978b871527e0fec2eda/examples/expressions.rb) for examples. Sorry for the slow response. I was gone on a 6 week trip.

**Comment by onesneakymofo** [comment]
@jnunemaker and co., this is beautiful.  I was just thinking about how to implement features for different mobile app versions and it seems `expressions` / Rules will do the trick. Kepping an eye on this - thanks!

**Comment by marcogregorius** [comment]
@jnunemaker thanks for the incredible feature. I am looking to implement a percentage of time within a set of actors, ie when a feature flag is enabled for a User, but also have the percentage of time randomness for that User only. The Expressions would be a nice solution for this.

If you don't mind me asking, is there an estimate of when would this be released for open source?

**Comment by bkeepers** [comment]
@marcogregorius Expressions are currently in the `main` branch and will be released as beta in 1.1. We don't have a timeline for that, but should be within the next month or so.

**Comment by rnestler** [comment]
If you also have rubocop configured to warn about `Rails/ReversibleMigration: change_column is not reversible.`  one can use the following for the migration:

```ruby
class ChangeFlipperGatesValueToText < ActiveRecord::Migration[7.0]
  def up
    change_column :flipper_gates, :value, :text
  end

  def down
    change_column :flipper_gates, :value, :string
  end
end
```

**Comment by gs-deliverists-io** [comment]
Hi,

migration cannot be executed on `mysql` using `trilogy

```
BLOB/TEXT column 'value' used in key specification without a key length (Trilogy::ProtocolError)
```

any ideas?

**Comment by jnunemaker** [comment]
Can you drop the full migration file and the output of the command so we can investigate? I've used trilogy like once and had a bunch of issues. Ended up going back to mysql2.

**Comment by billkauf** [comment]
FWIW, installing my app chokes while initializing `Flipper::Adapters::ActiveRecord` during `rake db:schema:load`:
```
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "flipper_gates" does not exist (ActiveRecord::StatementInvalid)

LINE 10:  WHERE a.attrelid = '"flipper_gates"'::regclass
[...]
.../vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.2/lib/active_record/model_schema.rb:486:in `column_for_attribute'
.../vendor/bundle/ruby/3.2.0/gems/flipper-active_record-1.1.1/lib/flipper/adapters/active_record.rb:280:in `value_not_text?'
.../vendor/bundle/ruby/3.2.0/gems/flipper-active_record-1.1.1/lib/flipper/adapters/active_record.rb:57:in `initialize'
.../config/initializers/flipper.rb:5:in `new'
[...]
```
(Paths are elided for clarity.)

I had to eat the `ActiveRecord::StatementInvalid`. Here's my new initializer:
```ruby
require 'flipper/adapters/active_record'

Flipper.configure do |config|
  config.default do
    adapter = Flipper::Adapters::ActiveRecord.new
    Flipper.new(adapter)
  rescue ActiveRecord::StatementInvalid
    # Ignore this
  end
end
```

**Comment by jnunemaker** [comment]
@billkauf thanks for reporting. Working on a fix. https://github.com/flippercloud/flipper/pull/786

**Comment by BrandonHicks-msr** [comment]
@gs-deliverists-io

I'm seeing this as well, with the exact same migration as @rnestler has posted above.

**Comment by bkeepers** [comment]
@fer9305 @BrandonHicks-msr @gs-deliverists-io 

Does this fix the error for you?

```diff
- change_column(:flipper_gates, :value, :text)
+ change_column(:flipper_gates, :value, :text, size: 65535)
```

**Comment by fer9305** [comment]
@bkeepers 

now it fails with a different error
```bash
== 20231211183249 ChangeFlipperGatesValueToText: migrating ====================
-- change_column(:flipper_gates, :value, :text, {:size=>65535})
rails aborted!
StandardError: An error has occurred, all later migrations canceled: (StandardError)

65535 is invalid :size value. Only :tiny, :medium, and :long are allowed.
db/migrate/20231211183249_change_flipper_gates_value_to_text.rb:4:in `up'

Caused by:
ArgumentError: 65535 is invalid :size value. Only :tiny, :medium, and :long are allowed. (ArgumentError)
db/migrate/20231211183249_change_flipper_gates_value_to_text.rb:4:in `up'
Tasks: TOP => db:migrate
```

however, if I pass `:medium` instead of `65535` it raises the original error
```ruby
Caused by:
ActiveRecord::StatementInvalid: Mysql2::Error: BLOB/TEXT column 'value' used in key specification without a key length (ActiveRecord::StatementInvalid)
```

**Comment by bkeepers** [comment]
Ok, I'm able to duplicate locally now, so I'll work on a fix here soon.

**Comment by bkeepers** [comment]
I opened another issue to talk specifically about this MySQL issue. Let's move conversation over there https://github.com/flippercloud/flipper/issues/789
